from nameh_khan.page_reader.utils.indexer import TopRightIndexer
from nameh_khan.page_reader.utils.segmentation import SimpleSegmentation
from nameh_khan.page_reader.utils.text_builder import LineBasedTextBuilder
